-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT_SUM) AS SALES
FROM 
PRODUCT P, (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT_SUM FROM OFFLINE_SALE 
GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;